apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
  labels:
    tier: webapi
    app: web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: loyolastalin/stalin-web-api:v6
        ports:
         - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

