apiVersion: v1
kind: Service
metadata:
  name: web-api-service
spec:
  type: LoadBalancer
  selector:
    tier: webapi
    app: web-api
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 8080 # Container Port