apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi-appsettings-config
data:
  appsettings.configmap.json: |-
    {
      "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
    },
  
    "MyConfigKey": "MyConfigValue from configMap"
    }