apiVersion: v1
kind: Secret
metadata:
  name: sqldb-connection-string
type: Opaque
data:
  db-password: U2VydmVyPTE5Mi4xNjguMC4xMDEsIDE0MzM7RGF0YWJhc2U9cHJvZHVjdDtVc2VyIElkPXNhO1Bhc3N3b3JkPXBhc3N3b3JkITtUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU=


