apiVersion: v1
kind: Service
metadata:
  name: web-api-service
  labels:
    app: web-api
spec:
  type: NodePort
  selector:
    app: web-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
